name: iciwi
main: mikeshafter.iciwi.iciwi
version: 1.0-SNAPSHOT
author: mikeshafter
depend: [Vault]
commands:
  checkfare:
    description: Checks fare
    usage: /checkfare <from> <to>
    permission: iciwi.cf
    permission-message: You don't have <permission>!
permissions:
  iciwi.cf:
    default: true