# This sets the penalty amount when someone forgets to tap in/out
penalty: 8.0
# Discount for transferring
transfer-discount: 0.6
# max time allowed for transfer
max-transfer-time: 300000
# time to wait until a fare gate closes, in ticks
gate-close-delay: 100
# ticket machine type (STATION, COMPANY, GLOBAL)
ticket-machine-type: STATION
#ticket-machine-type: COMPANY
#ticket-machine-type: GLOBAL