# This sets the penalty amount when someone forgets to tap in/out
penalty: 8.0

# This sets the deposit that a player pays when they buy a new card
deposit: 5.0

# Prices listed when buying a new Iciwi card
price-array: [10.0, 20.0, 30.0, 50.0, 100.0]

# Database
database: jdbc:sqlite:IciwiCards.db

# max time allowed for transfer
max-transfer-time: 300000

# time to wait until a fare gate closes, in ticks
gate-close-delay: 100

# ticket machine type (STATION, COMPANY, GLOBAL)
ticket-machine-type: STATION
#ticket-machine-type: COMPANY
#ticket-machine-type: GLOBAL

# global operator name (if GLOBAL is selected above)
global-operator: ExampleOperator

# default train class
default-class: 'Second Class'

# global ticket price
global-ticket-price: 5.0

# glass fare gate speed
ticks-to-open: 20
ticks-to-close: 20

# custom item usage
card:
  material: NAME_TAG
  custom-model-data: 0