# This sets whether the plugin should open the fare gate when someone forgets to tap in/out
open-on-penalty: true

# This sets the penalty amount when someone forgets to tap in/out
penalty: 8.0

# This sets the deposit that a player pays when they buy a new card
deposit: 5.0

# This sets the minimum amount that a card can have to enter the network.
min-amount: 3.0

# Prices listed when buying a new Iciwi card
price-array: [10.0, 20.0, 30.0, 50.0, 100.0]

# Database
database: jdbc:sqlite:IciwiCards.db

# max time allowed for transfer
max-transfer-time: 300000

# time to wait until a fare gate closes, in ticks
gate-close-delay: 100

# time to wait until a fare gate closes after a player walks through, in ticks
close-after-pass: 5

# default operator's name
global-operator: ExampleOperator

# default train class. An underscore prefix makes the train class only accessible by card
default-class: _Second

# global ticket price
global-ticket-price: 5.0

# glass fare gate speed
ticks-to-open: 20
ticks-to-close: 20

# custom item usage
card:
  material: NAME_TAG
  custom-model-data: 0

ticket:
  material: PAPER
  custom-model-data: 0

# usage passwords
a: password
b: password
c: password
d: password
