name: Iciwi
version: 1.17.1a5
main: mikeshafter.iciwi.Iciwi
api-version: 1.17
description: Iciwi plugin for Limaru
depend: [ Vault ]

commands:
  checkfare:
    usage: /<command> <from> <to>
    description: Checks fare.
    permission: iciwi.checkfare
  ticketmachine:
    usage: /<command> <station>
    description: Ticket machine.
    permission: iciwi.ticketmachine
  traindestroydelay:
    usage: /<command>
    description: Turns off automatic train destroy, resets after 1h automatically.
    permission: iciwi.traindestroydelay
  newdiscount:
    usage: /<command> <serial> <operator> <days before expiry>
    description: Adds a rail pass ("discounts") onto existing cards
    permission: iciwi.newdiscount
  redeemcard:
    usage: /<command> <number>. E.g. /redeemcard IA-12345
    description: Redeems an existing card with the stated serial number.
    permission: iciwi.redeemcard
  reloadconfig:
    usage: /<command>
    description: Reloads owners.yml
    permission: iciwi.reload
  coffers:
    usage: /<command> <empty|view> [(if "empty") company name]
    description: Withdraws/view coffers
    permission: iciwi.coffers


permissions:
  iciwi.*:
    description: Gives access to all Iciwi commands
    children:
      iciwi.checkfare: true
      iciwi.ticketmachine: true
      iciwi.traindestorydelay: true
      iciwi.newdiscount: true
      iciwi.reload: true
      iciwi.coffers: true
    default: op
  iciwi.checkfare:
    description: Allows the use of /checkfare
    default: true
  iciwi.ticketmachine:
    description: Allows the use of /ticketmachine
    default: op
  iciwi.traindestroydelay:
    description: Allows the use of /traindestroydelay
    default: op
  iciwi.newdiscount:
    description: Allows the use of /newdiscount
    default: op
  iciwi.redeemcard:
    description: Allows the use of /redeemcard
    default: op
  iciwi.reload:
    description: Allows the use of all reload commands
    default: op
  iciwi.coffers:
    description: Allows the use of /coffers
    default: op
  iciwi.coffers.viewall:
    description: Makes /coffers view show all companies
    default: false
