name: Iciwi
version: 1.16.4r2
main: mikeshafter.iciwi.Iciwi
api-version: 1.16
description: Iciwi plugin for Limaru

commands:
  checkFare:
    usage: /<command> <from> <to>
    description: Checks fare.
  ticketmachine:
    usage: /<command> <station>
    description: Ticket machine.
  settraindestroy:
    usage: /<command>
    description: Turns off automatic train destroy, resets after 1h automatically.
